<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE movies [
        <!ELEMENT movies (movie*)>
        <!ELEMENT movie (actors, date)>
        <!ELEMENT actors (actor*)>
        <!ELEMENT date (#PCDATA)>
        <!ATTLIST movie
                id CDATA #REQUIRED
                name CDATA #REQUIRED>

        <!ELEMENT actor (#PCDATA)>
        <!ATTLIST actor
                name CDATA #REQUIRED>

        ]>

<movies>
  <movie id= "academy_awards_3" name="The Social Network">
     <actors>
         <actor name="Jesse Eisenberg" />
     </actors>
     <date>2010-09-24</date>
   </movie>
   <movie id= "academy_awards_4" name="The King's Speech">
      <actors>
        <actor name="Colin Firth"></actor>
        <actor name="Geoffrey Rush"></actor>
        <actor name="Helena Bonham Carter"></actor>
      </actors>
      <date>2010-09-04</date>
   </movie>
</movies>
